[config]
schemaVersion = "0.0.1"

[package]
namespace = "GravitonGamer"
name = "MT2UnlimitedPurchases"
versionNumber = "1.0.2"
description = "A mod for Monster Train 2 that allows unlimited purchases and rerolls at merchants."
websiteUrl = "https://github.com/Jace17/MT2UnlimitedPurchases"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.4.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


